
/*
export const FETCH_ARTICLE_DETAILS = "FETCH_ARTICLE_DETAILS";
export const SET_ARTICLE_DETAILS = "SET_ARTICLE_DETAILS";
*/

export const MUTATE_LOCATION = 'MUTATE_LOCATION'
export const RELOAD_LIST = 'RELOAD_LIST'

/*
export const API = "API";
*/

export const API_START = "API_START";
export const API_END = "API_END";
export const ACCESS_DENIED = "ACCESS_DENIED";
export const API_ERROR = "API_ERROR";


//----

export const CLOUD_OFFLINE = 'CLOUD_OFFLINE'
export const CLOUD_ONLINE = 'CLOUD_ONLINE'
export const CLOUD_UPLOAD = 'CLOUD_UPLOAD'
export const CLOUD_DOWNLOAD = 'CLOUD_DOWNLOAD'

export const POST_COMMENT = 'POST_COMMENT'
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS'
export const POST_COMMENT_ERROR = 'POST_COMMENT_ERROR'

export const POST_COMMAND = 'POST_COMMAND'
export const POST_COMMAND_SUCCESS = 'POST_COMMAND_SUCCESS'
export const POST_COMMAND_ERROR = 'POST_COMMAND_ERROR'

export const TOGGLE_SETTING = 'TOGGLE_SETTING'

export const SET_MESSAGE_COUNT = 'SET_MESSAGE_COUNT'

export const CREATE_LOCATION = 'CREATE_LOCATION'
export const UPDATE_LOCATION = 'UPDATE_LOCATION'

export const RELOAD_LIST_RESP = 'RELOAD_LIST_RESP'

export const FETCH_EVENTS = 'FETCH_EVENTS'
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS'
export const FETCH_EVENTS_ERROR = 'FETCH_EVENTS_ERROR'
export const EVENT_ENTRY_UPDATE = 'EVENT_ENTRY_UPDATE'
export const EVENT_LIST = 'EVENT_LIST'

export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION'
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS'


